version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
        #- yum update -y
        #- yum install -y gcc-c++.x86_64
      - yum groupinstall "Development Tools"
      - yum install -y cmake3.x86_64
  build:
    commands:
       - echo Entered the build phase...
       - cmake3 .
       - make -j 2

artifacts:
  files:
    - install.sh

