version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
        #- yum update -y
      - yum search c++
      - yum install -y gcc-c++.x86_64
      - yum install -y g++-6
      - yum install -y cmake3.x86_64
      - yum groupinstall "Development Tools"
  build:
    commands:
       - echo Entered the build phase...
       - cmake .
       - make -j 2

artifacts:
  files:
    - install.sh

