version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y g++-6
      - apt-get install -y cmake
      - apt-get install -y build-essential
  build:
    commands:
       - echo Entered the build phase...
       - cmake .
       - make -j 2

artifacts:
  files:
    - install.sh

