version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
        #- yum update -y
        #- yum install -y gcc-c++.x86_64
      - yum groupinstall -y "Development Tools"
      - yum install -y cmake3.x86_64
  build:
    commands:
       - echo Entered the build phase...
       - mkdir build
       - cd build
       - cmake3 ../
       - make -j 
       - cd ../

artifacts:
  files:
    - build/minizinc
    - build/libmzn.a

